### ISSUE TITLE
Failed for setting parameter of remove_duplicate_patients 

### ISSUE THREAD

**Issue by wanhui5867** [getzlab/MutSig2CV#1]
Hi,

I have paired primary/metastatic samples, so I need to stop removing duplicate patients. But I tried several methods, none of them is successful. Here are tried methods:

1. Create a parameter file with remove_duplicate_patients = false, the parameter file is below:
number_of_categories_to_discover        5
skip_permutations       false
maxperm 1e5
remove_duplicate_patients       false

2. Create a parameter file with remove_duplicate_patients = 0
number_of_categories_to_discover        5
skip_permutations       false
maxperm 1e5
remove_duplicate_patients       0

3. Change src/MutSig_2CV_v3_11_core.m Line70: `P = impose_default_value(P,'remove_duplicate_patients',1);` to 
`P = impose_default_value(P,'remove_duplicate_patients',0);` 

All of them showed that removing the duplicated samples as below: 
```
Warning: Unable to open display 'localhost:30.0'.  You will not be able to display graphics on the screen.

MUTSIG_VERSION =

2CV v3.11

Warning: "FixedWidthBinary.jar" is already specified on static java path.
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 102
  In MutSig_2CV_v3_11_core at 27
  In MutSig_2CV_v3_11_wrapper at 51
LOADING DATA
Processing target list.
Loading mutations...
Keeping 223357/223519 unique mutations.
Scanning for duplicate patients...
Comparing on the basis of coding mutations only...
convert_chr: assuming human for chrX/chrY
24 patients involved in an overlap.
11 cliques of overlapping samples.
15 unique samples.
Removing the following 13 duplicate patients:
    'MC101D'
``` 

Could you give me some suggestions about giving false to remove_duplicate_patients? 

Thanks in advance!
Hui

**Comment by julianhess** [comment]
You need to run on mutations that are unique to each clone (i.e., you must exclude truncal mutations from the metastatic samples). The MutSig background model assumes that mutations in each sample arose independently. This assumption is violated if any mutations clonally inherited, as is the case with primaries -> metastases.

There is no option to disable the duplicate patient filter because there are no good reasons to do so.
