### ISSUE TITLE
reference genome

### ISSUE THREAD

**Issue by HengqiLiu** [getzlab/MutSig2CV#10]
Hi getzlab team：

What should I do to get mutsig2CV to run if the reference genome for my maf file alignment is `hg38`

Thank you！
Hengqi Liu

**Comment by julianhess** [comment]
Hi Hengqi,

Are you working with whole exomes or whole genomes? This will determine the reference files that you'll use.

—Julian

**Comment by HengqiLiu** [comment]
Hi Julian, 

I am working with whole exome sequencing data from next generation sequencing. 

—Hengqi

**Comment by HengqiLiu** [comment]
Hi Julian,

I am working with whole exome  data from next generation sequencing.

—Hengqi

**Comment by julianhess** [comment]
In that case, please download the following reference files from Google Cloud using `gsutil`:

```
gs://getzlab-workflows-reference_files-oa/MutSig2CV/hg38/coverage_models.agilent.mat
gs://getzlab-workflows-reference_files-oa/MutSig2CV/hg38/target_list.gencode25.txt
gs://getzlab-workflows-reference_files-oa/MutSig2CV/hg38/context_and_effect_track.fwb
gs://getzlab-workflows-reference_files-oa/MutSig2CV/hg38/context_and_effect_track.fwi
gs://getzlab-workflows-reference_files-oa/MutSig2CV/hg38/covariates.agilent.txt
```

and populate a tab-delimited files called `params.txt` with the following:

```
skip_permutations       True
coverage_models_mat_file        coverage_models.agilent.mat
target_list_file        target_list.gencode25.txt
context_and_effect_fwb_file     context_and_effect_track.fwb
context_and_effect_fwi_file      context_and_effect_track.fwi
covariates_file        covariates.agilent.txt
```

Note that you need to either copy the reference files into the directory you're running MutSig from, or specify the full path to each reference file.

Then run MutSig by passing the path to the `params.txt` file as a third argument, as detailed [here](https://github.com/getzlab/MutSig2CV#running-).

**Comment by HengqiLiu** [comment]
Thank you very much for your prompt help !!!

Best Wishes,
Hengqi Liu

**Comment by emucaki** [comment]
I apologize for re-opening this ticket, but is there credentials that I require to download the files listed above from the Google Cloud? I'm not experienced with 'gsutil', and all my attempts to download these files (with "gsutil cp" command) end in a "do not have storage.objects.get access to the Google Cloud Storage object" error. I'm not sure if its a problem with my setup or the files themselves.  

Thank you.

**Comment by cbravo93** [comment]
I am having the same issue:

``
AccessDeniedException: 403 XXX@gmail.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
``
Any solution?

Carmen

**Comment by lh12565** [comment]
Hi, @julianhess  Does the skip_permutations parameter have to be true for hg38 or optional?   Thanks!

**Comment by vmurigneu** [comment]
Hi @julianhess 
I am also unable to download the references files for hg38 

gsutil -m cp -r gs://getzlab-mutsig2cv-reference-files/hg38/ . 

AccessDeniedException: 403 XXXX@gmail.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
CommandException: 1 file/object could not be transferred.

Thank you

**Comment by xizhihui** [comment]
Hi, @lh12565 
sorry to bother you. Could you please share the reference files on hg38 if there is a backup? No way to download them. Orz

**Comment by lh12565** [comment]
Hi, @xizhihui   I've uploaded the MutSig2CV hg38 reference files to Zenodo for easier access. You can download them here: [MutSig2CV Reference Files (hg38) – Mirror](https://zenodo.org/records/18265601)
**Important Note**: This is just an unofficial mirror of the reference files. For guaranteed accuracy and updates, I strongly recommend downloading the official files from the Broad Institute as mentioned by julianhess above.

**Comment by xizhihui** [comment]
@lh12565 Wow. Thank you very much!!! It helps me a lot. Access to the official files on google cloud was expired :(
