### ISSUE TITLE
HG38 Reference Dataset

### ISSUE THREAD

**Issue by emucaki** [getzlab/MutSig2CV#12]
Good day,

In May 2022, there was a ticket asking for the hg38 reference genome MutSig2CV reference files ([link](https://github.com/getzlab/MutSig2CV/issues/10)) for exome data. These files were then provided by a Google Cloud link. 

All my attempts to download these files (with "gsutil cp" command) result in a "do not have storage.objects.get access to the Google Cloud Storage object" error. Are the files still in this location to be downloaded? I'm not experienced with the 'gsutil' command, but I receive the exact same error message if I purposely misspell the file I'm attempting to download, which makes me question if they are still present along that path.

Any help would be most appreciated. Thank you.

**Comment by rajeha** [comment]
I am having the same issue. Closed the separate issue so solution will be easily accessible here!

**Comment by julianhess** [comment]
Please find the relevant reference files in `gs://getzlab-mutsig2cv-reference-files/hg38`.
