### ISSUE TITLE
str2doubleq Function

### ISSUE THREAD

**Issue by virdzek-g** [getzlab/MutSig2CV#13]
Hello

I am trying to run MutSig2CV however I am stuck on the following error.

> MUTSIG_VERSION =
> 
>     2CV v3.11
> 
> LOADING DATA
> Processing target list.
> Unrecognized function or variable 'str2doubleq'.
> 
> Error in str2doubleq_wrapper (line 3)
> out = real(str2doubleq(in));
> 
> Error in make_numeric (line 37)
>       x = str2doubleq_wrapper(x);
> 
> Error in MutSig_2CV_v3_11_core (line 99)
> M.targ = make_numeric(M.targ,{'start','end'});
> 
> Error in MutSig2CV (line 51)
> G = MutSig_2CV_v3_11_core(args{:});
> 
> Error in startup (line 6)
> MutSig2CV('mutation_file.maf', '/Users/gv974/Documents/GitHub/MutSig2CV')
>  
> 

Could you please help me solve this, please?
Gabriela

**Comment by julianhess** [comment]
Are you trying to run this on a Mac? `str2doubleq` is a compiled MEX binary that only works on 64 bit Linux.

If you have access to the MATLAB compiler, you can try recompiling it for your system.

**Comment by virdzek-g** [comment]
Thank you so much for your reply. Yes I am working on Mac and I don't have access to MatLab compiler. May I ask whether there is any other way for me to run MutSig2CV, please?
Best regards
Gabriela

**Comment by virdzek-g** [comment]
I will put below what worked for me to solve this

It is not necessary to cross-compile; the GIT repository includes the .cpp source code (and the .c sources needed for different .mex* files.)
Unfortunately, the repository does not include a build script.

Installing XCode (not command line tools)

Then in MATLAB,
```
mex -setup C++
mex -setup C

mex str2doubleq.cpp
mex count_overlaps_fast2.c
mex hist2d_fast.c 
mex projection_1d_convolutions_fast.c
```
