### ISSUE TITLE
reference files: link down?

### ISSUE THREAD

**Issue by rajeha** [getzlab/MutSig2CV#14]
Thank you for sharing this tool. I am trying to run this on a maf file using the provided references (dictionary, coverage, covariates, etc.), but I am unable to download them. I believe the link provided in the Readme is down. Would you please share an alternate mirror?

Thanks!

**Comment by virdzek-g** [comment]
I think this should work for you
http://software.broadinstitute.org/cancer/cga/sites/default/files/data/tools/mutsig/MutSig2CV.tar.gz

**Comment by rajeha** [comment]
> I think this should work for you http://software.broadinstitute.org/cancer/cga/sites/default/files/data/tools/mutsig/MutSig2CV.tar.gz

Nothing happened when I clicked on the link. However, I looked into the issue and it turns out that Chrome was blocking the download. I fixed it by changing `http `to `https`. Thanks!

**Comment by rajeha** [comment]
@virdzek-g would you please help with this follow up. I am having an issue using a custom target list. Since I want to use the hg38 reference. I extracted the hg38 exons in the same format as the provided targets and renamed them as the original target file. MutSig now gives the following error: 

```
Looking up values in context_and_effect track
Category discovery....
Attempted to access ct(0,2); index must be a positive integer or logical.

Error in crosstab_full (line 25)

Error in hist2d (line 27)

Error in MutSig_2CV_v3_11_core (line 354)

Error in MutSig_2CV_v3_11_wrapper (line 50)

MATLAB:badsubscript
```

Is there any additional step necessary to make MutSig accept these new hg38 targets? Here is a snapshot of them:

> gene    chr     start   end
> DDX11L1 1       11869   12227
> DDX11L1 1       12613   12721
> DDX11L1 1       13221   14409
> WASH7P  1       14404   14501
> WASH7P  1       15005   15038
> WASH7P  1       15796   15947
> WASH7P  1       16607   16765
> WASH7P  1       16858   17055
> WASH7P  1       17233   17368

**Comment by julianhess** [comment]
You cannot simply update the target list to get it to work with hg38. You need to use an entirely new set of reference files, which is detailed here: https://github.com/getzlab/MutSig2CV/issues/10#issuecomment-1142375852

**Comment by rajeha** [comment]
@julianhess I am having the same problem as the last commenter in that thread:

`ServiceException: 401 Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.`

This is using gsutil cp command

**Comment by rajeha** [comment]
@virdzek-g @julianhess any luck updating access permissions on the files? sorry for the double mention but I feel like this is a valuable tool and would hate not to use it for a technical issue

**Comment by julianhess** [comment]
Hi,

**Comment by julianhess** [comment]
Please find the reference files here in this publicly accessible bucket: `gs://getzlab-mutsig2cv-reference-files/hg38`
