### ISSUE TITLE
undefined symbol when I ran MutSig2CV on Linux.

### ISSUE THREAD

**Issue by liux2250** [getzlab/MutSig2CV#15]
Hi,

I downloaded MutSig2CV and installed Matlab Runtime R2013a. 
When I tried to run MutSig2CV, I got the following error.
**./MutSig2CV: symbol lookup error: ./MutSig2CV: undefined symbol: _Z14standaloneMainRKSt6vectorISsSaISsEEbb**

I have already set the LD_LIBRARY_PATH before I ran it.

Did anyone encounter this error before? If so, could you give me some guidance about how to address this issue?
Thanks in advance.

Best,
Yang

**Comment by julianhess** [comment]
Hi Yang,

What operating system are you running?

**Comment by liux2250** [comment]
Hi,
Thanks for your prompt response!

I ran it on our HPC server. The system is running Redhat Enterprise Linux.
The Linux version is:
Linux 3.10.0-1160.15.2.el7.x86_64 #1 SMP Thu Jan 21 16:15:07 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

Best,
Yang

**Comment by liux2250** [comment]
Hi,

I ran it on my computer with Ubuntu Linux and it works.
I think MutSig2CV maybe need to be recompiled on Redhat Enterprise Linux.

Best,
Yang

**Comment by julianhess** [comment]
It's possible that the precompiled C/C++ .mex files are binary incompatible with RHEL. If you have access to the MATLAB compiler on your HPC cluster, try recompiling those files with `mex` and then rebuilding the MutSig executable with `mcc -m -I src -d bin -o MutSig2CV src/MutSig2CV`.

The C/C++ files that need to be rebuilt are:

* https://github.com/getzlab/MutSig2CV/blob/master/src/count_overlaps_fast2.c
* https://github.com/getzlab/MutSig2CV/blob/master/src/hist2d_fast.c
* https://github.com/getzlab/MutSig2CV/blob/master/src/projection_1d_convolutions_fast.c
* https://github.com/getzlab/MutSig2CV/blob/master/src/str2doubleq.cpp

**Comment by liux2250** [comment]
Hi Julianhess,

This problem was solved by recompiling those files. Thank you for your response. I really appreciate.

Best

**Comment by julianhess** [comment]
Great, glad that worked!
