### ISSUE TITLE
MUTSIG_VERSION =  2CV v3.11          Not found: reference/mutation_type_dictionary.v4.txt

### ISSUE THREAD

**Issue by amootta** [getzlab/MutSig2CV#7]
Hi, Ive been trying to run Mutsig2CV. 
I have downloaded the references file, and copied them to the same directory as the bin folder (in which the MutSig2CV executable is in). I've tried running: 
bin/MutSig2CV <full path to mutation file> <full path to output folder> 
But it has given me this error still: 
MUTSIG_VERSION =

2CV v3.11

        Not found: reference/mutation_type_dictionary.v4.txt
Error using demand_file (line 31)
1 file not found

Error in MutSig_2CV_v3_11_core (line 16)

Error in MutSig_2CV_v3_11_wrapper (line 51)

Where am I meant to copy my reference folder to? 
Thanks very much

**Comment by julianhess** [comment]
Copy the reference folder to parent directory of `bin`.
